"""Shared constants: run states, statuses and audit event names."""

from __future__ import annotations

ZERO_HASH = "0" * 64
ROUTING_POLICY_VERSION = "1"

# --- run state machine -------------------------------------------------------
CREATED = "CREATED"
DISCOVERING = "DISCOVERING"
DISCOVERY_COMPLETE = "DISCOVERY_COMPLETE"
HASHING = "HASHING"
INVENTORY_COMPLETE = "INVENTORY_COMPLETE"
CLASSIFYING = "CLASSIFYING"
CLASSIFIED = "CLASSIFIED"
REVIEW_REQUIRED = "REVIEW_REQUIRED"
PLANNING = "PLANNING"
PLAN_READY = "PLAN_READY"
BATCHES_GENERATED = "BATCHES_GENERATED"
EXTERNAL_EXECUTION_OBSERVED = "EXTERNAL_EXECUTION_OBSERVED"
RECONCILING = "RECONCILING"
RECONCILED = "RECONCILED"

RUN_STATES = (
    CREATED, DISCOVERING, DISCOVERY_COMPLETE, HASHING, INVENTORY_COMPLETE,
    CLASSIFYING, CLASSIFIED, REVIEW_REQUIRED, PLANNING, PLAN_READY,
    BATCHES_GENERATED, EXTERNAL_EXECUTION_OBSERVED, RECONCILING, RECONCILED,
)

# There is intentionally no EXECUTING state: Python never executes batches.
ALLOWED_TRANSITIONS: dict[str, frozenset[str]] = {
    CREATED: frozenset({DISCOVERING}),
    DISCOVERING: frozenset({DISCOVERY_COMPLETE}),
    DISCOVERY_COMPLETE: frozenset({HASHING}),
    HASHING: frozenset({INVENTORY_COMPLETE, HASHING}),
    INVENTORY_COMPLETE: frozenset({CLASSIFYING}),
    CLASSIFYING: frozenset({CLASSIFIED, REVIEW_REQUIRED, CLASSIFYING}),
    CLASSIFIED: frozenset({CLASSIFYING, PLANNING}),
    REVIEW_REQUIRED: frozenset({CLASSIFYING, PLANNING}),
    PLANNING: frozenset({PLAN_READY}),
    PLAN_READY: frozenset({PLANNING, BATCHES_GENERATED}),
    BATCHES_GENERATED: frozenset({PLANNING, EXTERNAL_EXECUTION_OBSERVED}),
    EXTERNAL_EXECUTION_OBSERVED: frozenset({RECONCILING}),
    RECONCILING: frozenset({RECONCILED}),
    RECONCILED: frozenset({RECONCILING}),
}

# --- inventory ---------------------------------------------------------------
ROOT_SOURCE = "SOURCE"
ROOT_TARGET = "TARGET"

HASH_PENDING = "PENDING"
HASH_HASHING = "HASHING"
HASH_HASHED = "HASHED"
HASH_FAILED = "FAILED"
HASH_UNSTABLE = "UNSTABLE"
HASH_BLOCKED_HARDLINK = "BLOCKED_HARDLINK"
HASH_TERMINAL = (HASH_HASHED, HASH_FAILED, HASH_UNSTABLE, HASH_BLOCKED_HARDLINK)

# --- routing -----------------------------------------------------------------
DESCEND = "DESCEND"
REVIEW = "REVIEW"
RESERVED_TARGET_IDS = frozenset({DESCEND, REVIEW})

SUBJECT_DIRECTORY = "DIRECTORY"
SUBJECT_FILE = "FILE"
SOURCE_JEV = "JEV"
SOURCE_HUMAN = "HUMAN"
DECISION_OK = "OK"
DECISION_API_FAILED = "API_FAILED"

ROUTE_DIRECT = "DIRECT"
ROUTE_INHERITED = "INHERITED_DIRECTORY"
ROUTE_READY = "READY"
ROUTE_REVIEW = "REVIEW"
ROUTE_BLOCKED = "BLOCKED"

# --- planning ----------------------------------------------------------------
OP_SAFE_MOVE = "SAFE_MOVE"
PLAN_READY_STATUS = "READY"
PLAN_REVIEW = "REVIEW"
PLAN_BLOCKED = "BLOCKED"
PLAN_NOOP = "NOOP"

# --- audit -------------------------------------------------------------------
SRC_PYTHON = "PYTHON"
SRC_BASH = "BASH"
SRC_RECONCILER = "RECONCILER"
SRC_HUMAN = "HUMAN"

# Events a generated Bash script is allowed to emit through `audit emit`.
BASH_EVENT_TYPES = frozenset({
    "BATCH_OPERATION_STARTED", "SOURCE_PRECHECK_OK", "SOURCE_PRECHECK_FAILED",
    "SOURCE_CHANGED_AFTER_INVENTORY", "SOURCE_CHANGED_DURING_COPY",
    "COPY_STARTED", "COPY_FINISHED", "COPY_FAILED",
    "TEMP_TARGET_HASH_VERIFIED", "TARGET_HASH_MISMATCH",
    "TARGET_COMMIT_STARTED", "TARGET_COMMITTED", "TARGET_COMMIT_FAILED",
    "TARGET_APPEARED_AFTER_PLAN", "TARGET_COLLISION",
    "FINAL_TARGET_HASH_VERIFIED", "FINAL_TARGET_HASH_MISMATCH",
    "SOURCE_DELETE_STARTED", "SOURCE_DELETED", "SOURCE_DELETE_FAILED",
    "OPERATION_COMPLETED", "OPERATION_ALREADY_COMPLETE",
    "OPERATION_RESUMED_AFTER_TARGET_COMMIT", "OPERATION_FAILED",
    "DATA_MISSING",
})

# Bash events that mean an operation did not finish successfully.
BASH_FAILURE_EVENTS = frozenset({
    "SOURCE_PRECHECK_FAILED", "SOURCE_CHANGED_AFTER_INVENTORY",
    "SOURCE_CHANGED_DURING_COPY", "COPY_FAILED", "TARGET_HASH_MISMATCH",
    "TARGET_COMMIT_FAILED", "TARGET_APPEARED_AFTER_PLAN", "TARGET_COLLISION",
    "FINAL_TARGET_HASH_MISMATCH", "SOURCE_DELETE_FAILED", "OPERATION_FAILED",
    "DATA_MISSING",
})
BASH_SUCCESS_EVENTS = frozenset({"OPERATION_COMPLETED", "OPERATION_ALREADY_COMPLETE"})

# --- reconciliation ----------------------------------------------------------
REC_VERIFIED_MOVED = "VERIFIED_MOVED"
REC_NOT_EXECUTED = "NOT_EXECUTED"
REC_BOTH_PRESENT = "TARGET_PRESENT_SOURCE_PRESENT"
REC_TARGET_MISMATCH = "TARGET_HASH_MISMATCH"
REC_SOURCE_CHANGED = "SOURCE_CHANGED"
REC_BOTH_MISSING = "SOURCE_MISSING_TARGET_MISSING"
REC_BLOCKED = "BLOCKED"

SUPPORTED_CHECKSUM_ALGORITHMS = ("sha256",)
